//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_04._03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.СодержимоеЗаказа = new HashSet<СодержимоеЗаказа>();
        }
    
        public int Номер { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public int КодПунктаВыдачи { get; set; }
        public int КодПользователя { get; set; }
        public string КодДляПолучения { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктыВыдачи ПунктыВыдачи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СодержимоеЗаказа> СодержимоеЗаказа { get; set; }
    }
}
