//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_04._03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.СодержимоеЗаказа = new HashSet<СодержимоеЗаказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public decimal Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория { get; set; }
        public int Скидка { get; set; }
        public int КоличествовоНаСкладе { get; set; }
        public string Описание { get; set; }
        public string Фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СодержимоеЗаказа> СодержимоеЗаказа { get; set; }
    }
}
